name: pullrequest
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - run: make dev
      - run: make test
      - run: make build
